//===----------------------------------------------------------------------===//
// 
// This is the top file for intrinsic definition of RISC-V Raccoon extension.
//
//===----------------------------------------------------------------------===//

// Include upstream intrinsic tablegen file.
include "Intrinsics.td"
// Include Raccoon extension intrinsic tablegen file.
include "IntrinsicsRISCVRaccoonExt.td"
